# define cases constant
from enum import Enum
class Cases(Enum):
    CASE_ONE_CORNER_IN_IGNORING_ZONE = 0
    CASE_TWO_CORNERS_IN_IGNORING_ZONE = 1
    CASE_FOUR_CORNERS_IN_IGNORING_ZONE = 2
    CASE_TWO_IGNORE_CORNERS_IN_RECT = 3
    CASE_FOUR_IGNORE_CORNERS_IN_RECT = 4
    CASE_CROSS_ZONES =5

